#!/bin/bash
#SBATCH --job-name=hierarchical-rema-train
#SBATCH --nodes=1
#SBATCH --cpus-per-gpu=4
#SBATCH --time=48:00:00
#SBATCH --mem=200gb
#SBATCH -p lem-gpu-short
#SBATCH --gpus-per-node=hopper:4
#SBATCH --verbose

set -euo pipefail

export RUN_KIND=${RUN_KIND:-train}
export BACKEND=${BACKEND:-vllm}
export MODE=${MODE:-alternating}
export TASKS_PER_EPOCH=${TASKS_PER_EPOCH:-16}
export NUM_DECOMPOSITIONS=${NUM_DECOMPOSITIONS:-16}
export NUM_SELECTIONS=${NUM_SELECTIONS:-16}
export TEMPERATURE=${TEMPERATURE:-0.5}
export CONTROLLER_MAX_NEW_TOKENS=${CONTROLLER_MAX_NEW_TOKENS:-1024}
export WORKER_MAX_NEW_TOKENS=${WORKER_MAX_NEW_TOKENS:-512}
export ROLLOUT_TASK_BATCH_SIZE=${ROLLOUT_TASK_BATCH_SIZE:-16}
export CONTROLLER_BATCH_SIZE=${CONTROLLER_BATCH_SIZE:-16}
export WORKER_BATCH_SIZE=${WORKER_BATCH_SIZE:-16}
export ROLLOUT_PROGRESS_EVERY=${ROLLOUT_PROGRESS_EVERY:-1}
export ROLLOUT_LOG_MODE=${ROLLOUT_LOG_MODE:-best}
export ROLLOUT_LOG_DETAIL=${ROLLOUT_LOG_DETAIL:-compact}
export BEST_K=${BEST_K:-1}
export CHECKPOINT_MODE=${CHECKPOINT_MODE:-all}
export PRUNE_STALE_POLICY_MODELS=${PRUNE_STALE_POLICY_MODELS:-true}
export SAVE_STEPS=${SAVE_STEPS:-0}
export EPOCH_S3_SYNC=${EPOCH_S3_SYNC:-true}
export EPOCH_S3_SYNC_INTERVAL=${EPOCH_S3_SYNC_INTERVAL:-120}
export ENABLE_WANDB=${ENABLE_WANDB:-true}

SOURCE_DIR=${SLURM_SUBMIT_DIR:-$(pwd)}
exec bash "$SOURCE_DIR/hierarchical-rema-trainer.sh" "$@"
