#!/bin/bash
#SBATCH --job-name=hierarchical-rema-train-rolechanged
#SBATCH --nodes=2
#SBATCH --cpus-per-gpu=4
#SBATCH --time=168:00:00
#SBATCH --mem=200gb
#SBATCH -p lem-gpu-normal
#SBATCH --gpus-per-node=hopper:4
#SBATCH --verbose
#SBATCH --exclude=r10-8,r12-1
#SBATCH --gres=storage:local:500G

set -euo pipefail

# High-level training preset for the hierarchical trainer wrapper.
# Keep this file opinionated and short: commonly tuned experiment knobs live here,
# while low-level defaults remain in hierarchical-rema-trainer.sh.

export RUN_KIND=${RUN_KIND:-train}

# Experiment shape.
export BACKEND=${BACKEND:-vllm}
export MODE=${MODE:-alternating}
export PARAMETER_SHARING=${PARAMETER_SHARING:-true}
export LEARNING_RATE=${LEARNING_RATE:-5e-6}
export ENTROPY_COEFF=${ENTROPY_COEFF:-0.001}
# Preferred subset-based names for the hierarchical training loop:
#   TRAIN_SUBSET_ROUNDS = number of outer rounds
#   TRAIN_SUBSET_SIZE   = tasks per outer round
#   GRPO_PASSES_PER_SUBSET = replay passes over one rollout subset
export TRAIN_SUBSET_ROUNDS=${TRAIN_SUBSET_ROUNDS:-${NUM_EPOCHS:-250}}
export GRPO_PASSES_PER_SUBSET=${GRPO_PASSES_PER_SUBSET:-${EPOCHS:-1}}
export TRAIN_SUBSET_SIZE=${TRAIN_SUBSET_SIZE:-${TASKS_PER_EPOCH:-128}}

# Search width and rollout cadence.
export NUM_DECOMPOSITIONS=${NUM_DECOMPOSITIONS:-16}
export NUM_SELECTIONS=${NUM_SELECTIONS:-16}
export ALTERNATING_SELECTOR_NUM_DECOMPOSITIONS=${ALTERNATING_SELECTOR_NUM_DECOMPOSITIONS:-4}
export ALTERNATING_SELECTOR_NUM_SELECTIONS=${ALTERNATING_SELECTOR_NUM_SELECTIONS:-4}
export ALTERNATING_DECOMPOSER_NUM_DECOMPOSITIONS=${ALTERNATING_DECOMPOSER_NUM_DECOMPOSITIONS:-8}
export ALTERNATING_DECOMPOSER_NUM_SELECTIONS=${ALTERNATING_DECOMPOSER_NUM_SELECTIONS:-2}
export SOFT_MAX_HOPS=${SOFT_MAX_HOPS:-5}
export HARD_MAX_HOPS=${HARD_MAX_HOPS:-8}
export MAX_NODES_PER_DECOMPOSITION=${MAX_NODES_PER_DECOMPOSITION:-$HARD_MAX_HOPS}
export SOFT_HOP_PENALTY=${SOFT_HOP_PENALTY:-0.1}
export ROLLOUT_TASK_BATCH_SIZE=${ROLLOUT_TASK_BATCH_SIZE:-48}
export UPDATE_EVERY_N_ROLLOUT_BATCHES=${UPDATE_EVERY_N_ROLLOUT_BATCHES:-1}
export ROLLOUT_PROGRESS_EVERY=${ROLLOUT_PROGRESS_EVERY:-10}

# Generation behavior.
export TEMPERATURE=${TEMPERATURE:-0.3}
export CONTROLLER_TEMPERATURE=${CONTROLLER_TEMPERATURE:-$TEMPERATURE}
export WORKER_TEMPERATURE=${WORKER_TEMPERATURE:-$TEMPERATURE}
export CONTROLLER_CONSTRAINED_DECODING=${CONTROLLER_CONSTRAINED_DECODING:-true}
export CONTROLLER_MAX_NEW_TOKENS=${CONTROLLER_MAX_NEW_TOKENS:-1024}
export DECOMPOSER_MAX_NEW_TOKENS=${DECOMPOSER_MAX_NEW_TOKENS:-1024}
export SELECTOR_MAX_NEW_TOKENS=${SELECTOR_MAX_NEW_TOKENS:-96}
export WORKER_MAX_NEW_TOKENS=${WORKER_MAX_NEW_TOKENS:-512}
export CONTROLLER_BATCH_SIZE=${CONTROLLER_BATCH_SIZE:-32}
export WORKER_BATCH_SIZE=${WORKER_BATCH_SIZE:-32}

# Distributed rollout / learner runtime.
export RAY_NNODES=${RAY_NNODES:-${SLURM_JOB_NUM_NODES:-2}}
export RAY_N_GPUS_PER_NODE=${RAY_N_GPUS_PER_NODE:-${SLURM_GPUS_ON_NODE##*:}}
export OFFLINE_GRPO_DISTRIBUTED=${OFFLINE_GRPO_DISTRIBUTED:-true}
export OFFLINE_GRPO_NNODES=${OFFLINE_GRPO_NNODES:-$RAY_NNODES}
export OFFLINE_GRPO_GPUS_PER_NODE=${OFFLINE_GRPO_GPUS_PER_NODE:-$RAY_N_GPUS_PER_NODE}
export VLLM_GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION:-0.7}
export VLLM_MAX_NUM_BATCHED_TOKENS=${VLLM_MAX_NUM_BATCHED_TOKENS:-16384}
export VLLM_MAX_NUM_SEQS=${VLLM_MAX_NUM_SEQS:-2048}

# Offline GRPO update cadence.
export TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-8}
export GRAD_ACCUM_STEPS=${GRAD_ACCUM_STEPS:-1}
export MAX_LENGTH=${MAX_LENGTH:-1024}
export GRADIENT_CHECKPOINTING=${GRADIENT_CHECKPOINTING:-false}
# Keep allocator tuning scoped to offline GRPO workers. vLLM rollout actors are
# incompatible with expandable_segments:True.
export OFFLINE_GRPO_PYTORCH_CUDA_ALLOC_CONF=${OFFLINE_GRPO_PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}

# Reward/training switches that are still commonly toggled in experiments.
export CONTROLLER_FORMAT_RETRY_PENALTY=${CONTROLLER_FORMAT_RETRY_PENALTY:-0.2} # subtract from controller reward/advantage when output needed repair
export CONTROLLER_FORMAT_FALLBACK_PENALTY=${CONTROLLER_FORMAT_FALLBACK_PENALTY:-0.25}
export FINAL_ANSWER_CORRECTNESS_REWARD_ONLY=${FINAL_ANSWER_CORRECTNESS_REWARD_ONLY:-false}
export TRAIN_MIN_REWARD=${TRAIN_MIN_REWARD:-}
# Controller sample provenance filter:
#   all = current behavior
#   no_fallback = drop fallback-derived controller samples
#   allow_local_repair = keep only clean or locally repaired controller samples
#   clean_only = keep only clean controller samples
export CONTROLLER_SAMPLE_QUALITY_FILTER=${CONTROLLER_SAMPLE_QUALITY_FILTER:-clean_only}
export DECOMPOSER_NO_CORRECT_SELECTION_SCALE=${DECOMPOSER_NO_CORRECT_SELECTION_SCALE:-0.5}
export DECOMPOSER_REWARD_AGGREGATION=${DECOMPOSER_REWARD_AGGREGATION:-mean}
export CONFIDENCE_REWARD_WEIGHT=${CONFIDENCE_REWARD_WEIGHT:-0.01}
export COMPATIBILITY_REWARD_WEIGHT=${COMPATIBILITY_REWARD_WEIGHT:-0.00}

export TRACK_WORKERS_HISTORY=${TRACK_WORKERS_HISTORY:-false}
export TRAIN_WORKER_MODEL=${TRAIN_WORKER_MODEL:-true}
export MIN_WORKER_GRPO_GROUP_SIZE=${MIN_WORKER_GRPO_GROUP_SIZE:-3}
export WORKER_LEARNING_RATE=${WORKER_LEARNING_RATE:-}
export WORKER_EPOCHS=${WORKER_EPOCHS:-}
export WORKER_CLIP_RANGE=${WORKER_CLIP_RANGE:-}


# External validation: keep it narrower and less frequent than training rollout.
export VAL_NUM_DECOMPOSITIONS=${VAL_NUM_DECOMPOSITIONS:-1}
export VAL_NUM_SELECTIONS=${VAL_NUM_SELECTIONS:-1}
export VAL_TEMPERATURE=${VAL_TEMPERATURE:-0.2}
export VAL_CONTROLLER_TEMPERATURE=${VAL_CONTROLLER_TEMPERATURE:-$VAL_TEMPERATURE}
export VAL_WORKER_TEMPERATURE=${VAL_WORKER_TEMPERATURE:-$VAL_TEMPERATURE}
export VAL_TOP_P=${VAL_TOP_P:-1.0}
export MAX_VAL_TASKS=${MAX_VAL_TASKS:-0}
export VAL_TASKS_PER_EPOCH=${VAL_TASKS_PER_EPOCH:-0}
export VAL_TASKS_PER_SUBSET=${VAL_TASKS_PER_SUBSET:-200}
export VAL_ROLLOUT_TASK_BATCH_SIZE=${VAL_ROLLOUT_TASK_BATCH_SIZE:-384}
export VAL_CONTROLLER_BATCH_SIZE=${VAL_CONTROLLER_BATCH_SIZE:-256}
export VAL_WORKER_BATCH_SIZE=${VAL_WORKER_BATCH_SIZE:-256}
export EXTERNAL_VALIDATION_EVERY_SUBSET_ROUNDS=${EXTERNAL_VALIDATION_EVERY_SUBSET_ROUNDS:-6}

# Logging / checkpointing defaults tuned for long runs.
export ROLLOUT_LOG_MODE=${ROLLOUT_LOG_MODE:-best}
export ROLLOUT_LOG_DETAIL=${ROLLOUT_LOG_DETAIL:-compact}
export BEST_K=${BEST_K:-1}
export CHECKPOINT_MODE=${CHECKPOINT_MODE:-all}
export SAVE_STEPS=${SAVE_STEPS:-200}
export EVAL_EVERY_STEPS=${EVAL_EVERY_STEPS:-20}
export EPOCH_S3_SYNC=${EPOCH_S3_SYNC:-true}
export EPOCH_S3_SYNC_INTERVAL=${EPOCH_S3_SYNC_INTERVAL:-120}
export PRUNE_STALE_POLICY_MODELS=${PRUNE_STALE_POLICY_MODELS:-true}
export PRUNE_UPLOADED_LOCAL_CHECKPOINTS=${PRUNE_UPLOADED_LOCAL_CHECKPOINTS:-true}
export STRIP_LOCAL_MODELS_AFTER_SYNC=${STRIP_LOCAL_MODELS_AFTER_SYNC:-true}
export ENABLE_WANDB=${ENABLE_WANDB:-true}

SOURCE_DIR=${SLURM_SUBMIT_DIR:-$(pwd)}
exec bash "$SOURCE_DIR/hierarchical-rema-trainer.sh" "$@"
