trainer:
  nnodes: 1
  n_gpus_per_node: 4

data:
  path: /root/tmpdir/agent0_data/train.parquet
  prompt_key: prompt
  n_samples: 16
  output_path: /root/tmpdir/agent12_data/teacher_candidates.parquet
  batch_size: 48
  resume_from_output: true
  checkpoint_every_batches: 5
  samples_per_call: 16

model:
  path: Qwen/Qwen2.5-1.5B-Instruct
  external_lib: null

rollout:
  name: vllm
  temperature: 1.0
  top_k: -1
  top_p: 0.95
  prompt_length: 4096
  response_length: 4096
  dtype: bfloat16
  gpu_memory_utilization: 0.8
  ignore_eos: False
  enforce_eager: True
  free_cache_engine: False
  load_format: dummy_dtensor
  tensor_model_parallel_size: 1
  max_num_batched_tokens: 16384
  max_model_len: 8192
  max_num_seqs: 512
  log_prob_micro_batch_size: null
  log_prob_micro_batch_size_per_gpu: 8
  use_fire_sampling: False
  do_sample: True
  disable_log_stats: True
  enable_chunked_prefill: True
  n: 16

actor:
  strategy: fsdp
  ulysses_sequence_parallel_size: 1
  fsdp_config:
    fsdp_size: -1
